version: 2
sources:
  - name: raw 
    schema: gz_raw_data
    tables:
      - name: product 
        identifier: raw_gz_product
        description: products in catalogue 
        columns:
          - name: products_id
            description: unique product id 
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the cost of acquiring the product /i think 
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90 
            period: day
        columns:
          - name: date_date
            description: date of purchase 
          - name: orders_id
            description: id of order
          - name: products_id
            description: id of product ordered 
          - name: revenue
            description: revenue generated by product sale in the order  
          - name: quantity
            description: amount of products sold in the order 
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: id of the order 
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the shipping fee collected on the order 
          - name: logcost
            description: the logistical cost of the order 
          - name: ship_cost
            description: the shipping cost of the order 
